apiVersion: v1
kind: Service
metadata:
  name: greeting-consumer
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: spring-consumer-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
